### ISSUE TITLE
Great Project - License?

### ISSUE THREAD

**Issue by ergodic1** [KevinBrtAltitude/react-rrule-widget#1]
This project is fantastic and much needed, what license is it under?
I also noticed that there are some translation keys missing in english:
```
days: {
    ...
    days: "day(s)",
```

**Comment by KevinBrtAltitude** [comment]
Hello,

Thanks !
It will be an MIT license.
I will update it soon to add the license, update the README, and fix translations

**Comment by ergodic1** [comment]
Thanks, much appreciated!
