### ISSUE TITLE
Idea: Indefinite end?

### ISSUE THREAD

**Issue by ergodic1** [KevinBrtAltitude/react-rrule-widget#2]
In the UI at the moment there is no way to specify that the recurrence should occur indefinitely.

![image](https://github.com/KevinBrtAltitude/react-rrule-widget/assets/1654795/f4c38854-e214-4015-bf02-a6a7e6807864)

Is that feasible?

**Comment by KevinBrtAltitude** [comment]
I will check on that

**Comment by KevinBrtAltitude** [comment]
It's published.

Thanks for the pull request !
