### ISSUE TITLE
NPM Auth Key

### ISSUE THREAD

**Issue by ergodic1** [KevinBrtAltitude/react-rrule-widget#3]
I noticed there's an auth key in the `.npmrc` in the repo. Probably worth rotating that key and removing it from git.
I had a look and it seems the package is not published on npm yet (https://www.npmjs.com/search?q=react-rrule-widget). 
Is that in the plan or should I fork and use this myself?

**Comment by KevinBrtAltitude** [comment]
Indeed, I've already removed the key from Git but it's still in the file, as planned. 
It's also planned that the package will be published on npm soon.

**Comment by KevinBrtAltitude** [comment]
It's live : https://www.npmjs.com/package/react-rrule-widget

**Comment by ergodic1** [comment]
Awesome!
